spring:

    datasource:
        url: jdbc:mysql://localhost:3306/bbs?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
    application:
        name: bbs
server:
    port: 8000

mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml # 如果使用 XML 文件
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 启用 SQL 打印
        map-underscore-to-camel-case: true # 启用驼峰命名
logging:
    level:
        com.itheima: debug
    pattern:
        dateformat: HH:mm:ss
